Adicionada a coluna _ID na projeção
A coluna _id é usada internamente pelo CursorAdapter e CursorLoader, entãos se ela não estiver na projeção uma exceção será lançada:

java.lang.IllegalArgumentException: column '_id' does not exist